sonar.projectKey=rent_car
sonar.organization=aminemechergui
sonar.projectName=rent_car

sonar.sources=src,auth-service/src,car-service/src,CustomerService/src,discovery-service/src,api-gateway/src,rental-service/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/build/**,**/.angular/**,**/.gradle/**

sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarcloud.io
