sonar.projectKey=YOUR_SONARCLOUD_PROJECT_KEY
sonar.organization=YOUR_SONARCLOUD_ORGANIZATION
sonar.projectName=car-rental-platform

sonar.sources=src,auth-service/src,car-service/src,CustomerService/src,discovery-service/src,api-gateway/src,rental-service/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/build/**,**/.angular/**,**/.gradle/**

sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarcloud.io
