server:
  port: 8086

spring:
  application:
    name: rental-service

  datasource:
    url: jdbc:mysql://localhost:3306/rent_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: myVerySecretKeyForCarRentalProject2026MyVerySecretKey
<<<<<<< HEAD
  expiration: 86400000
=======
  expiration: 86400000
>>>>>>> 9875c639 (version finale v01)
