apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: car-rental
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
  namespace: car-rental
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS auth_db;
    CREATE DATABASE IF NOT EXISTS car_db;
    CREATE DATABASE IF NOT EXISTS customer_db;
    CREATE DATABASE IF NOT EXISTS rent_db;
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: car-rental
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: car-rental
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.4
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data
        - name: mysql-initdb
          configMap:
            name: mysql-initdb
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: car-rental
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
